version: '3.7'

services:
  api:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo:latest
    container_name: db_mongo
    ports:
       - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=zombifier
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: